### ISSUE TITLE
Mean mass values of training dataset don't match when mean mass is calculated. The values are a bit off for all the cations. Does this happen for the composition of the 90 predicted composition as well?  

### ISSUE THREAD

**Issue by Yagnik12599** [jzhang-github/HECC_phase_prediction#1]

**Comment by jzhang-github** [comment]
> _No description provided._



Dear @Yagnik12599 

The mean mass values are calculated by averaging concentrations in the `POSCAR` file instead of the chemical formula. In the `POSCAR` file, the constituents may not have equal molar ratios.

I hope your concern is addressed.

**Comment by Yagnik12599** [comment]
Thanks! That makes sense.
Is there anyway I can know the feature values of the x_pred.txt correspond to which composition? Without the corresponding 90 compositions it is hard to know the model predicts 1 an d0 for which composition. If you can share the details, it would be really helpful. Thanks again!

**Comment by jzhang-github** [comment]
> Thanks! That makes sense. Is there anyway I can know the feature values of the x_pred.txt correspond to which composition? Without the corresponding 90 compositions it is hard to know the model predicts 1 an d0 for which composition. If you can share the details, it would be really helpful. Thanks again!

- If you are looking for the formulas of some input features, you may find this file useful: https://github.com/jzhang-github/HECC_phase_prediction/blob/main/docs/Input%20data.csv
- If you are looking for the formulas of [x_pred.txt](https://github.com/jzhang-github/HECC_phase_prediction/blob/main/ANN/x_pred.txt), you can find them at https://www.nature.com/articles/s41524-021-00678-3/tables/2 (I cannot guarantee because this paper was published years ago.)

**Comment by Yagnik12599** [comment]
Thanks! I understand that but I actually need the formulas with the feature values to be able to understand. Unfortunately the paper only has the predictions with formula and not the feature values.

But thanks anyways for the help!
